version: '3'

services:
  web:
    image: data-science-demos:0.1
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        PROXY: ${PROXY}
    env_file: .env
    ports:
      - 4000:4000
    volumes:
      - .:/opt/code
