name: Jekyllify projects
on:
  push:
    branches: ["staging"]
    paths:
      - '_projects/**'  # only run when PR makes changes to _projects folder contents
  
  workflow_dispatch:

jobs:
  jekyllify:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run jekyllify script
        run: python ./_utils/jekyllify.py
      - name: Create PR to main
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Jekyllifying project folder content
          branch: jekyllified_${{ github.ref_name }}
          delete-branch: true
          base: main
  