name: Jekyllify projects
run-name: ${{ github.actor }} project jekyllification
on: 
  push:
  pull_request:
    types:
      - closed  # only run when PR is merged (step 1)
    branches:
      - main  # only run on PRs to main branch
    paths:
      - '_projects/**'  # only run when PR makes changes to _projects folder contents
jobs:
  jekyllify-project-folders:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run jekyllify script
        run: python ./_utils/jekyllify.py
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto generate Jekyll front matter for projects